### PR TITLE
Add GitHub themes

### PR DESCRIPTION
**Pull request by ronilaukkarinen**
Adds to GitHub themes.

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
Could you please merge this? 🥺

**Comment by arniebradfo** [comment]
Woops, sorry @ronilaukkarinen, I never saw this...
I'll handle it the weekend.

**Comment by ronilaukkarinen** [comment]
Oh, cool! Just logged in to one of my site that had a plugin that overwrote my fork and hence I recalled the existence of this PR. So glad if you could merge it. Thanks in advance 🥰

**Comment by arniebradfo** [comment]
so...

I merged this, added the github dark theme too and tested all 3 new github themes. Turns out, the ones that github make don't work, but third-party one [codemirror-theme-github](https://www.npmjs.com/package/codemirror-theme-github) does. I'm going to leave that one in and take the other two out: [64b6baa](https://github.com/mukhortov/HESH-WordPress-Plugin/commit/6993ddd4dba27d52a0054e4867c4b78daec079fb). I'll release it soon.

But you got one in at least ⚽️ 🥅 👏

### Screenshots

#### [codemirror-theme-github](https://www.npmjs.com/package/codemirror-theme-github) 
Screen Shot 2021-09-17 at 5 54 55 PM

#### [codemirror-github-light](https://www.npmjs.com/package/codemirror-github-light) 
Screen Shot 2021-09-17 at 5 54 42 PM

#### [codemirror-github-dark](https://www.npmjs.com/package/codemirror-github-dark) 
Screen Shot 2021-09-17 at 5 54 16 PM

**Pull request merged**
